# Generated by Django 3.2.5 on 2021-07-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEnrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EnrollemntsForQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION_ID', models.IntegerField()),
                ('CATEGORY', models.CharField(max_length=50)),
                ('QUESTION', models.CharField(max_length=1000)),
                ('CORRECT', models.CharField(max_length=50)),
                ('CHOICE_1', models.CharField(max_length=50)),
                ('CHOICE_2', models.CharField(max_length=50)),
                ('CHOICE_3', models.CharField(blank=True, max_length=50)),
                ('CHOICE_4', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION_ID', models.IntegerField()),
                ('ACTUAL_QUESTION', models.CharField(max_length=1000)),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
                ('CATEGORY', models.CharField(max_length=50)),
                ('ANSWER', models.EmailField(max_length=254)),
                ('CORRECT_ANSWER', models.CharField(max_length=50)),
                ('START_TIME', models.DateTimeField(auto_now=True)),
                ('END_TIME', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
                ('GENDER', models.CharField(max_length=10)),
                ('SEMESTER', models.IntegerField()),
                ('SCHOOL', models.CharField(max_length=100)),
                ('PROGRAM', models.CharField(max_length=100)),
            ],
        ),
    ]
