# Generated by Django 3.2.5 on 2021-07-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0002_auto_20210717_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizdata',
            name='END_TIME',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='START_TIME',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
