# Generated by Django 3.1.5 on 2021-02-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0002_auto_20210219_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='CATEGORY',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='position',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='CHOICE_1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='CHOICE_2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='CHOICE_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='choice',
            name='CHOICE_4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='choice',
            name='CORRECT',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='choice',
            name='QUESTION',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='CATEGORY',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
