# Generated by Django 3.1.5 on 2021-02-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0003_auto_20210221_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='CATEGORY',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
