# Generated by Django 3.1.5 on 2021-02-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0004_auto_20210221_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='SR_NO',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
