# Generated by Django 3.2.5 on 2021-07-20 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0004_declare_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 23, 17, 20, 670770)),
        ),
        migrations.AddField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 23, 17, 20, 670746)),
        ),
    ]
