# Generated by Django 3.2.5 on 2021-07-24 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0005_auto_20210720_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 23, 40, 32, 222542)),
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 24, 23, 40, 32, 222506)),
        ),
        migrations.AlterField(
            model_name='question',
            name='CHOICE_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='CHOICE_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='CHOICE_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='CHOICE_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='CORRECT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='QUESTION',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='ACTUAL_QUESTION',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='ANSWER',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='CORRECT_ANSWER',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quizdata',
            name='ENROLLMENT_NUMBER',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ENROLLMENT_NUMBER',
            field=models.CharField(max_length=1000),
        ),
    ]
