# Generated by Django 3.1.5 on 2021-02-21 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0005_choice_sr_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Question',
        ),
    ]
