# Generated by Django 3.1.5 on 2021-02-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0006_auto_20210221_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('ENROLLMENT_NUMBER', models.IntegerField()),
                ('GENDER', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('SEMESTER', models.IntegerField()),
                ('SCHOOL', models.CharField(max_length=100)),
                ('PROGRAM', models.CharField(max_length=100)),
                ('CONTACT', models.IntegerField()),
            ],
        ),
    ]
