# Generated by Django 3.1.5 on 2021-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0007_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='GENDER',
            field=models.CharField(max_length=10),
        ),
    ]
