# Generated by Django 3.2.5 on 2021-07-26 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0007_auto_20210726_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='EMAIL',
            field=models.EmailField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 38, 29, 445316)),
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 26, 13, 38, 29, 445290)),
        ),
    ]
