# Generated by Django 3.1.5 on 2021-02-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0008_auto_20210222_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='NAME',
            new_name='FIRST_NAME',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='EMAIL',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='LAST_NAME',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
