# Generated by Django 3.2.5 on 2021-08-07 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0009_auto_20210729_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='GENDER',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizdata',
            name='SEMESTER',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 22, 2, 11, 169256)),
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 7, 22, 2, 11, 169223)),
        ),
    ]
