# Generated by Django 3.1.5 on 2021-02-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0009_auto_20210222_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='ENROLLMENT_NUMBER',
            field=models.CharField(max_length=100),
        ),
    ]
