# Generated by Django 3.1.5 on 2021-02-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0011_allowedenrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='CONTACT',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='GENDER',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='PROGRAM',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='SCHOOL',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='SEMESTER',
        ),
    ]
