# Generated by Django 3.1.5 on 2021-02-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0012_auto_20210225_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsEnrollments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
            ],
        ),
    ]
