# Generated by Django 3.2.5 on 2021-08-22 01:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0012_auto_20210822_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 1, 21, 54, 428279)),
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 1, 21, 54, 428249)),
        ),
    ]
