# Generated by Django 3.1.5 on 2021-02-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0013_studentsenrollments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentsEnrollments',
            new_name='EnrollemntsForQuiz',
        ),
    ]
