# Generated by Django 3.2.5 on 2021-08-23 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0013_auto_20210822_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='END_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 0, 4, 18, 688991)),
        ),
        migrations.AlterField(
            model_name='enrollemntsforquiz',
            name='START_TIME',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 0, 4, 18, 688961)),
        ),
    ]
