# Generated by Django 3.1.5 on 2021-02-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0014_auto_20210225_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='SR_NO',
            new_name='QUESTION_ID',
        ),
    ]
