# Generated by Django 3.1.5 on 2021-02-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0015_auto_20210226_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUESTION_ID', models.IntegerField()),
                ('ACTUAL_QUESTION', models.CharField(max_length=1000)),
                ('ENROLLMENT_NUMBER', models.CharField(max_length=100)),
                ('ANSWER', models.EmailField(max_length=254)),
                ('START_TIME', models.DateTimeField(blank=True)),
                ('END_TIME', models.DateTimeField(blank=True)),
            ],
        ),
    ]
