# Generated by Django 3.1.5 on 2021-02-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0016_quizdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizdata',
            name='END_TIME',
        ),
        migrations.RemoveField(
            model_name='quizdata',
            name='START_TIME',
        ),
    ]
