# Generated by Django 3.1.5 on 2021-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0017_auto_20210226_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='CORRECT_ANSWER',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='CORRECT',
            field=models.CharField(max_length=50),
        ),
    ]
