# Generated by Django 3.2.4 on 2021-06-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0019_quizdata_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='GENDER',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='PROGRAM',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='SCHOOL',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userregistration',
            name='SEMESTER',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
