# Generated by Django 3.2.5 on 2021-07-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declare_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESULT_STATUS', models.IntegerField(default=0)),
            ],
        ),
    ]
